version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py
  frontend:
    image: python:3.12-slim
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "8000:8000"
    command: python -m http.server 8000

